### PR TITLE
fix: undici headers

### LINKED ISSUE #287: Header encoding changes, leading to `ERR_INVALID_CHAR`
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.12.0

### Plugin version

8.3.1

### Node.js version

16.19.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

When a header is set using a character like `å` (Norwegian character) its encoding gets messed up. A fastify server serving it serializes correctly, but if `reply-from` is used, the encoding changes. If another server with `reply-from` is chained, the app crashes with `TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["content-disposition"]`.

### Steps to Reproduce

```js
const replyFrom = require('@fastify/reply-from');
const fastify = require('fastify');

const app = fastify();

app.get('/', (_request, reply) => {
  reply.header('content-disposition', 'år.pdf').send('OK');
});

app.listen({ port: 6666 });

const proxy = fastify();

proxy.register(replyFrom);

proxy.get('/', (_request, reply) => {
  return reply.from('http://localhost:6666');
});

proxy.listen({ port: 7777 });

const secondProxy = fastify();

secondProxy.register(replyFrom);

secondProxy.get('/', (_request, reply) => {
  return reply.from('http://localhost:7777');
});

secondProxy.listen({ port: 8888 });
```

```sh-session
$ curl -i http://localhost:6666
HTTP/1.1 200 OK
content-disposition: år.pdf
content-type: text/plain; charset=utf-8
content-length: 2
Date: Fri, 27 Jan 2023 15:47:49 GMT
Connection: keep-alive
Keep-Alive: timeout=72


$ curl -i http://localhost:7777
HTTP/1.1 200 OK
content-disposition: r.pdf
content-type: text/plain; charset=utf-8
content-length: 2
date: Fri, 27 Jan 2023 15:47:52 GMT
connection: keep-alive
keep-alive: timeout=72


$ curl -i http://localhost:8888
curl: (52) Empty reply from server
```

### Expected Behavior

The header should be correctly encoded and decoded (i.e. `7777` and `8888` should have the same result as `6666`).

If that's not possible I expect the first server to complain when the header is added.

### PR DESCRIPTION
**Pull request by climba03003**
Fixes #287 

Finally found the problem is caused by both `http` and `undici`.
1. `http` is not always treats the `header` to `latin1`.
https://github.com/nodejs/node/blob/2a29df64645a70bbb833298423a29206c4ec6a2e/lib/_http_outgoing.js#L361-L373
2. `undici` always perform `Buffer.from('').toString('utf8')` regardless the `header` encoding.
https://github.com/nodejs/undici/blob/2b260c997ad4efe4ed2064b264b4b546a59e7a67/lib/core/util.js#L216-L229

In combine of the above two problem.
The headers will parsed as a completely difference byte when chaining.

In this fix, we always treats the header as `latin1`. 
So, we are always consistence in the encoding.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -12,6 +12,31 @@ function filterPseudoHeaders (headers) {
...
 
+// http required the header to be encoded with latin1
+// undici will convert the latin1 buffer back to utf8
+// https://github.com/nodejs/undici/blob/2b260c997ad4efe4ed2064b264b4b546a59e7a67/lib/core/util.js#L216-L229
+// after chaining, the header will converted in wrong byte
+// Buffer.from('', 'latin1').toString('utf8') applied
+//
+// in order to presist the encoding, always encode it
+// back to latin1
+function patchUndiciHeaders (headers) {
```
Comment (SimenB) [inline lib/utils.js:23]: should there be an option in `undici` to leave headers as `latin1` encoding?

Comment (climba03003) [reply lib/utils.js:23]: I think yes. Otherwise, the `patch` is prone to error.

`undici` always trans-code the header. Maybe it should really detect the encoding before trans-code. That means the behavior should be identical to `http.request`.

Actually, I already open a issue on `undici`.
See https://github.com/nodejs/undici/issues/1903

**Review by mcollina — APPROVED** [review]
lgtm

File: lib/utils.js [hunk 2]
```diff
@@ -12,6 +12,31 @@ function filterPseudoHeaders (headers) {
   return dest
 }
 
+// http required the header to be encoded with latin1
```
Comment (SimenB) [inline lib/utils.js:15]:
```suggestion
// http requires the header to be encoded with latin1
```

File: lib/utils.js [hunk 3]
```diff
@@ -12,6 +12,31 @@ function filterPseudoHeaders (headers) {
...
+// undici will convert the latin1 buffer back to utf8
+// https://github.com/nodejs/undici/blob/2b260c997ad4efe4ed2064b264b4b546a59e7a67/lib/core/util.js#L216-L229
+// after chaining, the header will converted in wrong byte
+// Buffer.from('', 'latin1').toString('utf8') applied
+//
+// in order to presist the encoding, always encode it
```
Comment (SimenB) [inline lib/utils.js:21]:
```suggestion
// in order to persist the encoding, always encode it
```

File: lib/utils.js [hunk 4]
```diff
@@ -12,6 +12,31 @@ function filterPseudoHeaders (headers) {
   return dest
 }
 
+// http required the header to be encoded with latin1
+// undici will convert the latin1 buffer back to utf8
+// https://github.com/nodejs/undici/blob/2b260c997ad4efe4ed2064b264b4b546a59e7a67/lib/core/util.js#L216-L229
+// after chaining, the header will converted in wrong byte
```
Comment (SimenB) [inline lib/utils.js:18]:
```suggestion
// after chaining, the header will be serialised using wrong encoding
```

File: lib/utils.js [hunk 5]
```diff
@@ -12,6 +12,31 @@ function filterPseudoHeaders (headers) {
   return dest
 }
 
+// http required the header to be encoded with latin1
+// undici will convert the latin1 buffer back to utf8
```
Comment (SimenB) [inline lib/utils.js:16]:
```suggestion
// undici will convert the latin1 buffer to utf8
```

**Review by RafaelGSS — APPROVED** [review]

**Comment by mcollina** [comment]
Would this need a revert after undici is fixed?

**Comment by climba03003** [comment]
I believe, yes.

**Comment by arturkin** [comment]
FYI this causes regression with `set-cookie` headers in case it's an array of values. Had to revert to the previous version due to this.

**Comment by climba03003** [comment]
> FYI this causes regression with set-cookie headers in case it's an array of values. Had to revert to the previous version due to this.

Can you provide a reproducible code in a separate issue?

**Comment by SimenB** [comment]
The change can probably be reverted together with a bump of the `undici` dependency?

**Comment by climba03003** [comment]
> The change can probably be reverted together with a bump of the undici dependency?

Even with bumping `undici` in `dependencies`, I believe it wouldn't catch-up the latest.

**Comment by SimenB** [comment]
It would

**Comment by mcollina** [comment]
Could you open a fresh PR?
