### PR TITLE
Pass Fastify request to callbacks

### LINKED ISSUE #72: `rewriteRequestHeaders` unable to access request decorations
## 🐛 Bug Report

`rewriteRequestHeaders` unable to access request decorations

## To Reproduce

```js
fastify.decorateRequest('foo', null)
fastify.addHook('preHandler', async (request, reply) => {
  request.foo = 'Bar'
})
fastify.register(require('fastify-http-proxy'), {
  upstream: process.env.UPSTREAM,
  prefix: '/api',
  replyOptions: {
    rewriteRequestHeaders(originalReq, headers) {
      const modifiedHeaders = {
        ...headers,
        'x-foo': request.foo
      }
      return modifiedHeaders
    }
  }
})
```

## Expected behavior

I expect that the request decorations would be accessible via `rewriteRequestHeaders` via the `originalReq` parameter.

## Your Environment

- *node version*: 12
- *fastify version*: 2.13.1
- *os*: Mac

### PR DESCRIPTION
**Pull request by barronpm**
Fixes #72, related to #168.

Currently, the options `rewriteHeaders`, `rewriteRequestHeaders`, and `getUpstream` are all sync-only.
The suggested workaround in #168 was to use hooks to decorate the request, however, only `onResponse` passes in the fastify request, the others passed in the raw request, rendering the decorations inaccessible.

This PR updates the methods above to use the fastify request as the parameter. The old parameter is still accessible at `request.raw`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ const fastifyReplyFrom = fp(function from (fastify, opts, next) {
     }
 
     // we leverage caching to avoid parsing the destination URL
-    const dest = getUpstream(req, base)
+    const dest = getUpstream(this.request, base)
```
Comment (mcollina) [inline index.js:66]: We need a test for this change.

Comment (barronpm) [reply index.js:66]: There's already a test checking the type, is there something else you wanted to test for?

Comment (jsumners) [reply index.js:66]: If the current tests do not show a problem then they do not cover the change.

Comment (barronpm) [reply index.js:66]: I had to edit the tests to check for the new type, see my edits to `types/index.test-d.ts`

Comment (jsumners) [reply index.js:66]: This is a change to the actual code. There needs to be an associated unit test to guard against regression and assure that the data is being passed correctly.

Comment (barronpm) [reply index.js:66]: Alright, how do you want me to check whether the argument is a fastify request?

Comment (jsumners) [reply index.js:66]: That's the core of the work. How did you determine that it needs to be passed in? Write a test that fails your expectation without the change.

Comment (Eomm) [reply index.js:66]: right now: `req` is equals to `this.request.raw`, `this.request` is the fastify request.

In any case:

- this PR would be a breaking change
- we need to update docs
- tests must be updated to check that option functions get a fastify object

Comment (barronpm) [reply index.js:66]: I've added tests that check that the request passed in the callback is correct, and verified that those tests fail on master.

In terms of docs, I read through the README, but the docs never specified exactly what the type of the request parameter is, so I left it as-is. Do you want me to add that?

Comment (mcollina) [reply index.js:66]: Please add it, thanks!

Comment (barronpm) [reply index.js:66]: done

File: README.md [hunk 2]
```diff
@@ -292,21 +292,24 @@ The default behavior is `reply.send(error)`, which will be disabled if the
 option is specified.
 It must reply the error.
 
-#### `rewriteHeaders(headers, req)`
+#### `rewriteHeaders(headers, request)`
 
 Called to rewrite the headers of the response, before them being copied
 over to the outer response.
+Parameters are the original headers and the fastify request.
```
Comment (jsumners) [inline README.md:299]:
```suggestion
Parameters are the original headers and the Fastify request.
```

File: README.md [hunk 3]
```diff
@@ -292,21 +292,24 @@ The default behavior is `reply.send(error)`, which will be disabled if the
...
 It must return the new headers object.
 
-#### `rewriteRequestHeaders(originalReq, headers)`
+#### `rewriteRequestHeaders(request, headers)`
 
 Called to rewrite the headers of the request, before them being sent to the other server.
+Parameters are the fastify request and the original request headers.
```
Comment (jsumners) [inline README.md:305]:
```suggestion
Parameters are the Fastify request and the original request headers.
```

File: README.md [hunk 4]
```diff
@@ -292,21 +292,24 @@ The default behavior is `reply.send(error)`, which will be disabled if the
...
 It must return the new headers object.
 
-#### `getUpstream(originalReq, base)`
+#### `getUpstream(request, base)`
 
 Called to get upstream destination, before the request is being sent. Useful when you want to decide which target server to call based on the request data.
 Helpful for a gradual rollout of new services.
+Parameters are the fastify request and the base string from the plugin options.
```
Comment (jsumners) [inline README.md:312]:
```suggestion
Parameters are the Fastify request and the base string from the plugin options.
```

**Review by mcollina — APPROVED** [review]
lgtm
