### PR TITLE
Fix crash when target server is unavailable

### LINKED ISSUE #8: Crash: Source crashes when http2 target goes down or becomes unavailable
**Scenario 1:** 
Start source server without starting client. Source process crashes immediatly as it tries to create client connection eagerly.

**Scenario 2:**
1. Start target and then source 
2. Shutdown target service
3. Hit proxied request
Source server crashes as http2 client session becomes invalid after target shutdown

**Proposed Solution:**
1. Lazy initialization of `http2Client` on first request.
2. Setup `error` event listener on `http2Client`.
Planning to return status `500` with `Internal Server Error` as message. **_Any suggestions?_**
3. Check `http2Client.destroyed` flag to determine whether session is valid or not and attempt to reconnect.

Pull request will follow shortly.

### PR DESCRIPTION
**Pull request by nileshmali**
Fixes #8

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -66,7 +66,13 @@ module.exports = fp(function from (fastify, opts, next) {
     request({ method: req.method, url, qs, headers, body }, (err, res) => {
       if (err) {
         this.request.log.warn(err, 'response errored')
-        this.send(err)
+        if (!this.sent) {
+          if (err.code === 'ERR_HTTP2_STREAM_CANCEL') {
```
Comment (nileshmali) [inline index.js]: Not sure whether this is correct way or not. I am trying to avoid exposing internal error message which contains host address information of target.
Please suggest.

Comment (nileshmali) [reply index.js]: Error is already logged on line 68. Which should have all information.

File: lib/request.js [hunk 2]
```diff
@@ -56,12 +57,16 @@ function buildRequest (opts) {
   }
 
   function handleHttp2Req (opts, done) {
-    const isGet = opts.method === 'GET' || opts.method === 'get'
+    if (!http2Client || http2Client.destroyed) {
+      http2Client = http2.connect(baseUrl, { rejectUnauthorized })
+      http2Client.once('error', done)
```
Comment (mcollina) [inline lib/request.js]: this `done` call should be removed once the new client is connected.

**Comment by mcollina** [comment]
Can you please check if you have the latest version of avvio installed? We had a bug on a similar topic.

**Comment by nileshmali** [comment]
avvio version is `5.4.3` which is latest. Still have same result.

**Comment by mcollina** [comment]
You have to `await server.close()` in both occasions.

**Comment by nileshmali** [comment]
Seems like `server.close` does not return promise, which causes timeout error.

**Comment by mcollina** [comment]
I'm pretty certain that it does.

**Comment by nileshmali** [comment]
Yeah! You were right. Issue is with `http2` flag on target.
If you remove `got` calls `server.close()` works without any issue. But if you fire any request then `server.close()` does not work and times out. 
I suspect that, as Http2Server sessions are persistent they are still active after `got` request and hence preventing graceful shutdown of fastify server.

Is this related to below note from NodeJS documentation:
> Note that this is not analogous to restricting new requests since HTTP/2 connections are persistent. To achieve a similar graceful shutdown behavior, consider also using http2session.close() on active sessions.

**Comment by mcollina** [comment]
Part of the problem is that in https://github.com/nileshmali/fastify-reply-from/blob/21ec5dbb7130204d6c9065c54f32b19010138254/index.js#L94-L97 we don not wait for things to be shut down properly.

**Comment by nileshmali** [comment]
But I am not trying to close instance which has plugin registered. I am closing target instance which does not have any of the plugin installed.

**Comment by mcollina** [comment]
Can you please add the failing test to this PR? It'd be easier for me to help.

**Comment by nileshmali** [comment]
@mcollina Pushed failing test file, please take a look.

**Comment by mcollina** [comment]
It ended up being a node core bug on Http2: https://github.com/nodejs/node/issues/20630. The callback we pass to `close(cb)` is never called.

**Comment by mcollina** [comment]
Can you please remove the test?

**Comment by nileshmali** [comment]
Done

**Comment by mcollina** [comment]
Thanks @nileshmali! Would you like to help maintaining this?

**Comment by nileshmali** [comment]
Yes. I would be glad to do that. But have very less time during weekdays. 
My responses might be delayed.
